version: "3.3"

services:
  consul:
    image: "consul:1.10.1"
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    command: agent -server -bootstrap -ui -data-dir /tmp -client=0.0.0.0 

#    -bind=127.0.0.1

  mongodb:
    hostname: mongodb
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: votingControl-ms
      MONGO_REPLICA_SET_NAME: rs0
    volumes:
      - ./mongo-initdb.d:/docker-entrypoint-initdb.d
    expose:
      - 27017
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.slaveOk().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
   
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      - consul
      - mongodb
    ports:
     - "5672:5672"
     - "15672:15672"
     
#  votingcontrol:
#    image: "rubleske/votingcontrol:0.0.1-SNAPSHOT"
#    hostname: votingcontrol
#    container_name: votingcontrol
#    depends_on:
#      - consul
#      - mongodb
#      - rabbitmq3
#    ports:
#      - "30005:30005"
#    environment:
#      - SPRING_DATASOURCE_URL=mongodb://localhost:27017/votingControl-ms
